// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: brent.proto

package sdpconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	sdp_go "github.com/overmindtech/terraform-provider-overmind/go/sdp-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BrentServiceName is the fully-qualified name of the BrentService service.
	BrentServiceName = "brent.BrentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BrentServiceExecuteWorkflowProcedure is the fully-qualified name of the BrentService's
	// ExecuteWorkflow RPC.
	BrentServiceExecuteWorkflowProcedure = "/brent.BrentService/ExecuteWorkflow"
)

// BrentServiceClient is a client for the brent.BrentService service.
type BrentServiceClient interface {
	// Executes a workflow from a natural-language prompt. The server streams
	// events as the agent reasons, calls MCP tools, and produces a final result.
	// The stream ends with either a CompletionEvent or a terminal ErrorEvent.
	ExecuteWorkflow(context.Context, *connect.Request[sdp_go.ExecuteWorkflowRequest]) (*connect.ServerStreamForClient[sdp_go.ExecuteWorkflowResponse], error)
}

// NewBrentServiceClient constructs a client for the brent.BrentService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBrentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BrentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	brentServiceMethods := sdp_go.File_brent_proto.Services().ByName("BrentService").Methods()
	return &brentServiceClient{
		executeWorkflow: connect.NewClient[sdp_go.ExecuteWorkflowRequest, sdp_go.ExecuteWorkflowResponse](
			httpClient,
			baseURL+BrentServiceExecuteWorkflowProcedure,
			connect.WithSchema(brentServiceMethods.ByName("ExecuteWorkflow")),
			connect.WithClientOptions(opts...),
		),
	}
}

// brentServiceClient implements BrentServiceClient.
type brentServiceClient struct {
	executeWorkflow *connect.Client[sdp_go.ExecuteWorkflowRequest, sdp_go.ExecuteWorkflowResponse]
}

// ExecuteWorkflow calls brent.BrentService.ExecuteWorkflow.
func (c *brentServiceClient) ExecuteWorkflow(ctx context.Context, req *connect.Request[sdp_go.ExecuteWorkflowRequest]) (*connect.ServerStreamForClient[sdp_go.ExecuteWorkflowResponse], error) {
	return c.executeWorkflow.CallServerStream(ctx, req)
}

// BrentServiceHandler is an implementation of the brent.BrentService service.
type BrentServiceHandler interface {
	// Executes a workflow from a natural-language prompt. The server streams
	// events as the agent reasons, calls MCP tools, and produces a final result.
	// The stream ends with either a CompletionEvent or a terminal ErrorEvent.
	ExecuteWorkflow(context.Context, *connect.Request[sdp_go.ExecuteWorkflowRequest], *connect.ServerStream[sdp_go.ExecuteWorkflowResponse]) error
}

// NewBrentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBrentServiceHandler(svc BrentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	brentServiceMethods := sdp_go.File_brent_proto.Services().ByName("BrentService").Methods()
	brentServiceExecuteWorkflowHandler := connect.NewServerStreamHandler(
		BrentServiceExecuteWorkflowProcedure,
		svc.ExecuteWorkflow,
		connect.WithSchema(brentServiceMethods.ByName("ExecuteWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	return "/brent.BrentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BrentServiceExecuteWorkflowProcedure:
			brentServiceExecuteWorkflowHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBrentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBrentServiceHandler struct{}

func (UnimplementedBrentServiceHandler) ExecuteWorkflow(context.Context, *connect.Request[sdp_go.ExecuteWorkflowRequest], *connect.ServerStream[sdp_go.ExecuteWorkflowResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("brent.BrentService.ExecuteWorkflow is not implemented"))
}
