// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: brent.proto

package sdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteWorkflowRequest initiates a workflow run.
type ExecuteWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Natural-language instructions for the agent.
	// Example: "Look up ticket ENG-1234 in Linear, summarize it, post to #engineering in Slack"
	WorkflowPrompt string `protobuf:"bytes,1,opt,name=workflow_prompt,json=workflowPrompt,proto3" json:"workflow_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_brent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteWorkflowRequest) GetWorkflowPrompt() string {
	if x != nil {
		return x.WorkflowPrompt
	}
	return ""
}

// ExecuteWorkflowResponse is a single event in the execution stream.
// Each response carries a timestamp so the client can order events.
type ExecuteWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When this event was produced by the server.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The event payload. Exactly one field will be set per message.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteWorkflowResponse_Reasoning
	//	*ExecuteWorkflowResponse_ToolCall
	//	*ExecuteWorkflowResponse_ToolResult
	//	*ExecuteWorkflowResponse_Completion
	//	*ExecuteWorkflowResponse_Error
	//	*ExecuteWorkflowResponse_Status
	Event         isExecuteWorkflowResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_brent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteWorkflowResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetEvent() isExecuteWorkflowResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetReasoning() *ReasoningEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteWorkflowResponse_Reasoning); ok {
			return x.Reasoning
		}
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetToolCall() *ToolCallEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteWorkflowResponse_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetToolResult() *ToolResultEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteWorkflowResponse_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetCompletion() *CompletionEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteWorkflowResponse_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteWorkflowResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteWorkflowResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isExecuteWorkflowResponse_Event interface {
	isExecuteWorkflowResponse_Event()
}

type ExecuteWorkflowResponse_Reasoning struct {
	// A chunk of the agent's reasoning / LLM output text.
	Reasoning *ReasoningEvent `protobuf:"bytes,10,opt,name=reasoning,proto3,oneof"`
}

type ExecuteWorkflowResponse_ToolCall struct {
	// The agent is calling a tool on an MCP server.
	ToolCall *ToolCallEvent `protobuf:"bytes,11,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ExecuteWorkflowResponse_ToolResult struct {
	// The result returned from an MCP tool call.
	ToolResult *ToolResultEvent `protobuf:"bytes,12,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ExecuteWorkflowResponse_Completion struct {
	// The agent finished successfully.
	Completion *CompletionEvent `protobuf:"bytes,13,opt,name=completion,proto3,oneof"`
}

type ExecuteWorkflowResponse_Error struct {
	// A terminal error — the stream ends after this event.
	Error *ErrorEvent `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

type ExecuteWorkflowResponse_Status struct {
	// Operational progress (e.g. "Connecting to MCP servers...").
	Status *StatusEvent `protobuf:"bytes,15,opt,name=status,proto3,oneof"`
}

func (*ExecuteWorkflowResponse_Reasoning) isExecuteWorkflowResponse_Event() {}

func (*ExecuteWorkflowResponse_ToolCall) isExecuteWorkflowResponse_Event() {}

func (*ExecuteWorkflowResponse_ToolResult) isExecuteWorkflowResponse_Event() {}

func (*ExecuteWorkflowResponse_Completion) isExecuteWorkflowResponse_Event() {}

func (*ExecuteWorkflowResponse_Error) isExecuteWorkflowResponse_Event() {}

func (*ExecuteWorkflowResponse_Status) isExecuteWorkflowResponse_Event() {}

// ReasoningEvent carries a chunk of the agent's streaming output. Multiple
// ReasoningEvents form the full reasoning trace when concatenated in order.
type ReasoningEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A text chunk from the LLM's streaming response.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningEvent) Reset() {
	*x = ReasoningEvent{}
	mi := &file_brent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningEvent) ProtoMessage() {}

func (x *ReasoningEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningEvent.ProtoReflect.Descriptor instead.
func (*ReasoningEvent) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{2}
}

func (x *ReasoningEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ToolCallEvent is emitted when the LLM decides to invoke an MCP tool.
// The corresponding ToolResultEvent will share the same tool_call_id.
type ToolCallEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this tool invocation, used to correlate with
	// the matching ToolResultEvent. Passed through from the LLM response.
	ToolCallId string `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// Identifier of the MCP server that owns this tool
	// (e.g. "github", "linear", "slack").
	McpId string `protobuf:"bytes,2,opt,name=mcp_id,json=mcpId,proto3" json:"mcp_id,omitempty"`
	// The name of the tool being called (e.g. "search_issues").
	ToolName string `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Raw JSON string of the tool call arguments exactly as returned by the
	// LLM. We pass through the raw JSON rather than a Struct to keep the
	// proto simple and the streaming path fast — the frontend can parse or
	// display it as needed.
	ArgumentsJson string `protobuf:"bytes,4,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEvent) Reset() {
	*x = ToolCallEvent{}
	mi := &file_brent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEvent) ProtoMessage() {}

func (x *ToolCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEvent.ProtoReflect.Descriptor instead.
func (*ToolCallEvent) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallEvent) GetMcpId() string {
	if x != nil {
		return x.McpId
	}
	return ""
}

func (x *ToolCallEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallEvent) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// ToolResultEvent carries the result of an MCP tool call. A tool-level
// failure (is_error=true) is non-terminal: the agent loop feeds the error
// back to the LLM, which may retry or try a different approach.
type ToolResultEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches the tool_call_id from the corresponding ToolCallEvent.
	ToolCallId string `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// Identifier of the MCP server that executed the tool.
	McpId string `protobuf:"bytes,2,opt,name=mcp_id,json=mcpId,proto3" json:"mcp_id,omitempty"`
	// The content returned by the tool (text representation).
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// True when the tool call itself failed (e.g. MCP server error, tool
	// not found, invalid arguments). The agent loop treats this as a
	// recoverable error and continues execution.
	IsError       bool `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultEvent) Reset() {
	*x = ToolResultEvent{}
	mi := &file_brent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultEvent) ProtoMessage() {}

func (x *ToolResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultEvent.ProtoReflect.Descriptor instead.
func (*ToolResultEvent) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResultEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultEvent) GetMcpId() string {
	if x != nil {
		return x.McpId
	}
	return ""
}

func (x *ToolResultEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToolResultEvent) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// CompletionEvent signals the agent finished its work successfully.
// This is the final semantic event in the stream.
type CompletionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent's final output text.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionEvent) Reset() {
	*x = CompletionEvent{}
	mi := &file_brent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionEvent) ProtoMessage() {}

func (x *CompletionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionEvent.ProtoReflect.Descriptor instead.
func (*CompletionEvent) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{5}
}

func (x *CompletionEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ErrorEvent signals a terminal failure. The stream ends immediately
// after this event. Examples: LLM API unreachable, unrecoverable
// internal error, context deadline exceeded.
type ErrorEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable error description.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_brent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StatusEvent provides operational progress updates that are not part of
// the agent's reasoning. Useful for the UI to show what the system is
// doing before the LLM starts streaming (e.g. MCP server connections).
type StatusEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable status message.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_brent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_brent_proto_rawDescGZIP(), []int{7}
}

func (x *StatusEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_brent_proto protoreflect.FileDescriptor

const file_brent_proto_rawDesc = "" +
	"\n" +
	"\vbrent.proto\x12\x05brent\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\x16ExecuteWorkflowRequest\x12'\n" +
	"\x0fworkflow_prompt\x18\x01 \x01(\tR\x0eworkflowPrompt\"\x96\x03\n" +
	"\x17ExecuteWorkflowResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\treasoning\x18\n" +
	" \x01(\v2\x15.brent.ReasoningEventH\x00R\treasoning\x123\n" +
	"\ttool_call\x18\v \x01(\v2\x14.brent.ToolCallEventH\x00R\btoolCall\x129\n" +
	"\vtool_result\x18\f \x01(\v2\x16.brent.ToolResultEventH\x00R\n" +
	"toolResult\x128\n" +
	"\n" +
	"completion\x18\r \x01(\v2\x16.brent.CompletionEventH\x00R\n" +
	"completion\x12)\n" +
	"\x05error\x18\x0e \x01(\v2\x11.brent.ErrorEventH\x00R\x05error\x12,\n" +
	"\x06status\x18\x0f \x01(\v2\x12.brent.StatusEventH\x00R\x06statusB\a\n" +
	"\x05event\"*\n" +
	"\x0eReasoningEvent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x8c\x01\n" +
	"\rToolCallEvent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x15\n" +
	"\x06mcp_id\x18\x02 \x01(\tR\x05mcpId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x04 \x01(\tR\rargumentsJson\"\x7f\n" +
	"\x0fToolResultEvent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x15\n" +
	"\x06mcp_id\x18\x02 \x01(\tR\x05mcpId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\"+\n" +
	"\x0fCompletionEvent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\vStatusEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2b\n" +
	"\fBrentService\x12R\n" +
	"\x0fExecuteWorkflow\x12\x1d.brent.ExecuteWorkflowRequest\x1a\x1e.brent.ExecuteWorkflowResponse0\x01B1Z/github.com/overmindtech/workspace/go/sdp-go;sdpb\x06proto3"

var (
	file_brent_proto_rawDescOnce sync.Once
	file_brent_proto_rawDescData []byte
)

func file_brent_proto_rawDescGZIP() []byte {
	file_brent_proto_rawDescOnce.Do(func() {
		file_brent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brent_proto_rawDesc), len(file_brent_proto_rawDesc)))
	})
	return file_brent_proto_rawDescData
}

var file_brent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_brent_proto_goTypes = []any{
	(*ExecuteWorkflowRequest)(nil),  // 0: brent.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil), // 1: brent.ExecuteWorkflowResponse
	(*ReasoningEvent)(nil),          // 2: brent.ReasoningEvent
	(*ToolCallEvent)(nil),           // 3: brent.ToolCallEvent
	(*ToolResultEvent)(nil),         // 4: brent.ToolResultEvent
	(*CompletionEvent)(nil),         // 5: brent.CompletionEvent
	(*ErrorEvent)(nil),              // 6: brent.ErrorEvent
	(*StatusEvent)(nil),             // 7: brent.StatusEvent
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_brent_proto_depIdxs = []int32{
	8, // 0: brent.ExecuteWorkflowResponse.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: brent.ExecuteWorkflowResponse.reasoning:type_name -> brent.ReasoningEvent
	3, // 2: brent.ExecuteWorkflowResponse.tool_call:type_name -> brent.ToolCallEvent
	4, // 3: brent.ExecuteWorkflowResponse.tool_result:type_name -> brent.ToolResultEvent
	5, // 4: brent.ExecuteWorkflowResponse.completion:type_name -> brent.CompletionEvent
	6, // 5: brent.ExecuteWorkflowResponse.error:type_name -> brent.ErrorEvent
	7, // 6: brent.ExecuteWorkflowResponse.status:type_name -> brent.StatusEvent
	0, // 7: brent.BrentService.ExecuteWorkflow:input_type -> brent.ExecuteWorkflowRequest
	1, // 8: brent.BrentService.ExecuteWorkflow:output_type -> brent.ExecuteWorkflowResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_brent_proto_init() }
func file_brent_proto_init() {
	if File_brent_proto != nil {
		return
	}
	file_brent_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecuteWorkflowResponse_Reasoning)(nil),
		(*ExecuteWorkflowResponse_ToolCall)(nil),
		(*ExecuteWorkflowResponse_ToolResult)(nil),
		(*ExecuteWorkflowResponse_Completion)(nil),
		(*ExecuteWorkflowResponse_Error)(nil),
		(*ExecuteWorkflowResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brent_proto_rawDesc), len(file_brent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brent_proto_goTypes,
		DependencyIndexes: file_brent_proto_depIdxs,
		MessageInfos:      file_brent_proto_msgTypes,
	}.Build()
	File_brent_proto = out.File
	file_brent_proto_goTypes = nil
	file_brent_proto_depIdxs = nil
}
